### ISSUE TITLE
Cannot delete two posts

### ISSUE THREAD

**Issue by Hedurtado** [alshedivat/al-folio#2696] opened 2024-09-13 03:09 UTC
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Cannot delete two posts

### How to reproduce the bug

I went to `_posts` and I delete all the posts,.

### Error messages and logs

When the website redeploy two posts keep showing
![image](https://github.com/user-attachments/assets/c9c0b0bc-2d7e-4c66-84df-74d6874f2ca6)
the last 2

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Running locally with Docker

### More info

I already check all the folders, and I don't see where the last two posts is saved in order to delete them.

**Comment by george-gca** [comment] 2024-09-13 15:21
Duplicate of #798.

**Closed by george-gca** 2024-09-13 15:21 UTC
Labels: bug
