### ISSUE TITLE
My Gemfile and all folders that their names started with "_" vanish after successful deployment 

### ISSUE THREAD

**Issue by mh-malekpour** [alshedivat/al-folio#967] opened 2022-11-04 22:16 UTC
**Describe the bug**
My Gemfile and all folders that their names started with "_" vanish after successful deployment by `bin/deploy --user` command! I cannot see folders such as "_bibliography", "_data" and ... anymore. Why?

Repository: [link](https://github.com/mh-malekpour/mh-malekpour.github.io)

**Screenshots**
<img width="310" alt="image" src="https://user-images.githubusercontent.com/43685227/200082172-b9e21439-04d6-4683-a0d4-ad2f6cc37cbf.png">

**System (please complete the following information):**
 - OS: MacOS Ventura v13.0
 - Browser: Chrome
 - Jekyll version: 4.3.1
- Ruby version: 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin22]

**Comment by rohandebsarkar** [comment] 2022-11-11 20:18
Try without using the `--user`.

Duplicate of #820.

**Closed** 2022-11-11 20:22 UTC
Labels: bug
