### ISSUE TITLE
Cannot see the local version page using docker in README

### ISSUE THREAD

**Issue by InYongShin** [alshedivat/al-folio#829] opened 2022-08-20 17:29 UTC
OS: window 10 using MINGW

I want to check the edited page running local server with using `./bin/dockerhub_run.sh`.

After I run `./bin/dockerhub_run.sh` and connect the server, I see the second image below. (this means that cannot connect to site)

This is my process about I described above.
![image](https://user-images.githubusercontent.com/57998317/185759215-74fbb67c-52af-4816-b4c9-79852ca3b5dc.png)
![image](https://user-images.githubusercontent.com/57998317/185759218-baa449ae-5d57-4a38-b121-1bed4835cc76.png)

Thanks in advance !

**Comment by pourmand1376** [comment] 2022-09-06 00:14
What is this `winpty` thing? I haven't heard about it. I think the problem is that this `winpty` doesn't properly map port 8080 to windows. 

Have you tried windows `WSL`? That one should have no problem.

**Comment by lyubomirShoylev** [comment] 2022-09-10 09:36
Hi, I've had the same problem while trying to build with Docker in Windows and I think I have landed on a solution.

From what I can tell, there is some problem with how the file directories are managed when running the script for the Docker image, and `jekyll` can't find the `_config.yml` file, as evident by the message `Configuration file: none` after running the script.

I have tried running the `dockerhub_run.sh` script in several shell environments: Command Prompt, Git Bash, and PowerShell (the default version that comes with Windows is PS 5.x), and none of these worked.

What finally solved my problem was installing PowerShell 7 and running the bash script _in PS 7_ as
``` PowerShell
(repo-dir)> bash ./bin/dockerhub_run.sh
```
After that, I could open my page in the browser as usual at `http://localhost:8080/` and browse around.

I don't really know _why_ that fixed the problem (I'm not very well versed in these technologies and how they work under the hood), but I hope this will be of help :).

Note: I have WSL2 installed to facilitate all the Docker functionality as recommended.

**Comment by pourmand1376** [comment] 2022-09-10 12:26
I have installed windows recently and I will try `WSL` Ubuntu and write my experience here.

I am wondering why everyone thinks so complex ... Just using an Ubuntu inside wsl should be fine in my idea. However this should be tested. Maybe things aren't as simple.

**Comment by pourmand1376** [comment] 2022-09-11 09:32
I tested this thing, and I had some problems. So, I created a `docker-compose` file. Just add a file named `docker-compose.yml` in your main directory and fill it with these instructions. 

```
version: "3"

services:
  jekyll:
    image: amirpourmand/al-folio
    command: bundler exec jekyll serve --watch --port=8080 --host=0.0.0.0 --verbose
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
```
After that you can simply use `docker-compose up`.

**Closed** 2022-10-31 15:27 UTC
