### ISSUE TITLE
Main.js file not found

### ISSUE THREAD

**Issue by RishitToteja** [alshedivat/al-folio#2725] opened 2024-09-27 20:12 UTC
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

While deploying, getting the following error

### How to reproduce the bug

Following the video

### Error messages and logs

![Screenshot_20240928-013853](https://github.com/user-attachments/assets/b800cbda-9c35-4eb8-9fdd-1a68241ccbc3)

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Deployed site

**Comment by george-gca** [comment] 2024-09-27 21:00
> ## How to reproduce the bug
>
> Following the video

Which video?

What is your repo? What changes have you made to your repo?

Without more information there is not much we can do.

**Comment by FrayPozo** [comment] 2024-09-27 21:23
> Which video?
The author is referring to the video mentioned in here:  https://github.com/alshedivat/al-folio/blob/master/INSTALL.md

Which has the link to this video: https://github.com/alshedivat/al-folio/blob/master/assets/video/tutorial_al_folio.mp4

I am following the same instructions and wasn't able to reproduce the results in the video because I get the same error as the author of the post. This is the very first step you take when using this template.

**Comment by shuyijia** [comment] 2024-09-27 21:40
The same issue has been reported here: https://github.com/JamesIves/github-pages-deploy-action/issues/1697

Current fix is to modify Line 93 in `.github/workflows/deploy.yml` 

from
`JamesIves/github-pages-deploy-action@v4` 

to
`JamesIves/github-pages-deploy-action@v4.6.4`

**Comment by Yuer867** [comment] 2024-09-28 01:42
@shuyijia Thanks! It works out!

**Comment by george-gca** [comment] 2024-09-28 14:50
Since the `v4` major tag have been updated, I believe no changes on our side are needed. Closing this issue.

https://github.com/JamesIves/github-pages-deploy-action/issues/1697#issuecomment-2380614391

**Closed by george-gca** 2024-09-28 14:50 UTC
Labels: bug
