### ISSUE TITLE
Issues with running docker locally on Windows 10 

### ISSUE THREAD

**Issue by sidtechnical** [alshedivat/al-folio#1540] opened 2023-07-06 16:30 UTC
![image](https://github.com/alshedivat/al-folio/assets/2378582/4e571f6a-da97-4bee-bfef-6c14359a5a40)

Unsure if this is an issue with my PC or something with the al-folio docker image.

**Comment by george-gca** [comment] 2023-07-08 16:59
Please post the whole stacktrace here, as not only the pasted part doesn't give much info, but also the contrast of the error message is terrible.

**Comment by nicholaiTukanov** [comment] 2023-07-11 22:13
I have the same issue +1

**Comment by nicholaiTukanov** [comment] 2023-07-11 22:14
@george-gca here my stack trace

`al-folio-website  | bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
al-folio-website  | /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/frontmatter_defaults.rb:63:in `find': stack level too deep (SystemStackError)
al-folio-website  |     from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/document.rb:58:in `block in initialize'
al-folio-website  |     from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/drops/excerpt_drop.rb:19:in `name'
al-folio-website  |     from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/drops/drop.rb:128:in `public_send'
al-folio-website  |     from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/drops/drop.rb:128:in `[]'
al-folio-website  |     from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/drops/drop.rb:205:in `block in to_h'
al-folio-website  |     from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/drops/drop.rb:204:in `each'
al-folio-website  |     from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/drops/drop.rb:204:in `each_with_object'
al-folio-website  |     from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/drops/drop.rb:204:in `to_h'
al-folio-website  |      ... 9391 levels...
al-folio-website  |     from /var/lib/gems/3.1.0/gems/bundler-2.4.16/exe/bundler:4:in `load'
al-folio-website  |     from /var/lib/gems/3.1.0/gems/bundler-2.4.16/exe/bundler:4:in `<top (required)>'
al-folio-website  |     from /usr/local/bin/bundler:25:in `load'
al-folio-website  |     from /usr/local/bin/bundler:25:in `<main>'`

**Comment by george-gca** [comment] 2023-07-12 01:48
@nicholaiTukanov this happens with the code straight from the repo? Or did you change something already?

**Comment by nicholaiTukanov** [comment] 2023-07-12 02:29
@george-gca yes this occurs straight from the repo

**Comment by george-gca** [comment] 2023-07-12 13:41
No idea what that might be. Looking it up online, `stack level too deep` means that an infinite recursion might be occurring. The other error point to `display_categories` being `null` in `projects.md`.

This only happens on Windows with Docker and without changing a single line of code from the current main branch?

**Comment by pourmand1376** [comment] 2023-07-16 05:03
I have seen this issue on windows. I know that removing those files fixes the problem. However, I do not know how to fix it. 

It is also odd that it only happens on windows. Maybe something to do with docker itself.

**Comment by ElPavlillo** [comment] 2023-07-28 00:47
Same issue hear with the stock repo and windows 10.

**Comment by edwinfourriernicolai** [comment] 2023-09-05 11:10
I have the same issue. I have tried with Windows 10 and Linux with Docker and without changing a single line of code from the current main branch. The issue occurs only with Windows.

**Comment by dannyboy990** [comment] 2023-09-11 11:33
I had the same issue. removing _posts/2021-07-04-diagrams.md worked for me.

**Comment by fffmath** [comment] 2023-10-08 14:18
> I had the same issue. removing _posts/2021-07-04-diagrams.md worked for me.

Same to me.

**Comment by george-gca** [comment] 2023-10-11 23:16
@pourmand1376 is the mermaid dependency installed in the Dockerfile? Maybe this could be causing it. After I tackle #1609 maybe this issue changes?

**Comment by pourmand1376** [comment] 2023-10-12 18:51
@george-gca 
No. I don't think so. Shouldn't we include it in gemfile?

**Comment by george-gca** [comment] 2023-10-13 22:30
I would say it was not necessary since the [blog post](https://alshedivat.github.io/al-folio/blog/2021/diagrams/) about it works, but I just realized that we actually include it in the [deploy action](https://github.com/alshedivat/al-folio/blob/a21bd492bc9950f86f160baea1a2e31d3cc6227d/.github/workflows/deploy.yml#L39), but not in the Dockerfile, so yes, I believe we should.

**Comment by pourmand1376** [comment] 2023-10-21 16:52
> I would say it was not necessary since the [blog post](https://alshedivat.github.io/al-folio/blog/2021/diagrams/) about it works, but I just realized that we actually include it in the [deploy action](https://github.com/alshedivat/al-folio/blob/a21bd492bc9950f86f160baea1a2e31d3cc6227d/.github/workflows/deploy.yml#L39), but not in the Dockerfile, so yes, I believe we should.

I added that in gemfile, but the problem was not solved.

**Comment by george-gca** [comment] 2023-10-21 19:32
I believe only adding in the Gemfile doesn't solve this. You should also add the npm line that we use in the [deploy action](https://github.com/alshedivat/al-folio/blob/a21bd492bc9950f86f160baea1a2e31d3cc6227d/.github/workflows/deploy.yml#L39).

**Comment by gabrieldesouza02** [comment] 2023-10-26 02:56
started with the same issue as you guys, removed `_posts/2021-07-04-diagrams.md`  but that didn't help, removed `_pages/projects.md` and now I'm getting this error:

![image](https://github.com/alshedivat/al-folio/assets/47791612/77b8bed0-320c-40f0-b5c1-c18a0b2c0725)


that being said I have made some local changes though, my site is currently deployed and most of the changes are just on the landing page, if anybody thinks I may have changed something relevant I can look into what all my changes are exactly

**Comment by george-gca** [comment] 2023-11-22 19:50
Have your issue been solved @gabrieldesouza02?

**Comment by gabrieldesouza02** [comment] 2023-11-22 20:48
> Have your issue been solved @gabrieldesouza02?

no it hasn't sadly. I was thinking of cloning the repo again and start from scratch. I haven't made too many changes anyways.

**Comment by george-gca** [comment] 2023-11-23 14:42
It seems to be a problem with your pc accessing `docker.io`. Are you sure you can download docker images in this pc?

**Comment by gabrieldesouza02** [comment] 2023-11-25 19:18
I have run docker images on this pc before , I don't think that's the issue

**Comment by gabrieldesouza02** [comment] 2023-11-25 19:19
I actually haven't been touching project recently though, whenever I get back to it I'll probably try cloning the repo and starting from scratch

**Comment by pollostrazon** [comment] 2023-12-11 08:49
Hi, I am having the same connection problem pointed out above. It happens both on Windows and WSL. Any tips?

**Comment by pourmand1376** [comment] 2023-12-11 08:58
> Hi, I am having the same connection problem pointed out above. It happens both on Windows and WSL. Any tips?

Hi, Have you deleted this `diagram` file? If yes, please share your full log stacktrace.

**Comment by pollostrazon** [comment] 2023-12-11 09:04
> > Hi, I am having the same connection problem pointed out above. It happens both on Windows and WSL. Any tips?
> 
> Hi, Have you deleted this `diagram` file? If yes, please share your full log stacktrace.

Hi. Yes, since that file is deleted it's able to run both `docker compose pull` and `docker compose up`. The problem is that I get "Cannot establish connection" through my browser (Firefox, but I tried Chrome and the situation is unchanged) when trying to run the site locally.

I am now trying to build it with `docker compose up --build` and see whether something changes.

**Comment by pourmand1376** [comment] 2023-12-11 09:15
Can you use this and output the stacktrace?
```
docker run -p 8080:8080 --name jekyll -v $(pwd):/srv/jekyll amirpourmand/al-folio:v0.10.0
```

**Comment by pollostrazon** [comment] 2023-12-11 09:46
I couldn't include the -v option though cause it returns
`docker: invalid reference format.
See 'docker run --help'.`
Here is the log without it
```
Resolving dependencies...
  Logging at level: debug
    Jekyll Version: 4.3.2
Configuration file: none
  Logging at level: debug
    Jekyll Version: 4.3.2
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       EntryFilter: excluded /.jekyll-cache
       EntryFilter: excluded /Gemfile.lock
       EntryFilter: excluded /Gemfile
        Generating: JekyllGetJson::GetJsonGenerator finished in 4.6161e-05 seconds.
No config
        Generating: Jekyll::Scholar::DetailsGenerator finished in 1.5146e-05 seconds.
        Generating: Jekyll::Archives::Archives finished in 9.2438e-05 seconds.
        Generating: JekyllJupyterNotebook::Generator finished in 8.7702e-05 seconds.
       Jekyll Feed: Generating feed for posts
        Generating: JekyllFeed::Generator finished in 0.001702735 seconds.
       Imagemagick: Disabled in site.config
        Generating: JekyllImagemagick::ImageGenerator finished in 2.3921e-05 seconds.
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Disabled in site.config.
        Generating: Jekyll::PaginateV2::Generator::PaginationGenerator finished in 0.000267959 seconds.
        Generating: Jekyll::JekyllSitemap finished in 0.001565178 seconds.
         Rendering: feed.xml
  Pre-Render Hooks: feed.xml
  Rendering Liquid: feed.xml
  Rendering Markup: feed.xml
Post-Convert Hooks: feed.xml
  Rendering Layout: feed.xml
         Rendering: sitemap.xml
  Pre-Render Hooks: sitemap.xml
  Rendering Liquid: sitemap.xml
  Rendering Markup: sitemap.xml
Post-Convert Hooks: sitemap.xml
  Rendering Layout: sitemap.xml
         Rendering: robots.txt
  Pre-Render Hooks: robots.txt
  Rendering Liquid: robots.txt
  Rendering Markup: robots.txt
Post-Convert Hooks: robots.txt
  Rendering Layout: robots.txt
                    done in 0.024 seconds.
         Requiring: jekyll-watch
           Watcher: Ignoring (?-mix:^_site\/)
           Watcher: Ignoring (?-mix:^\.jekyll\-cache\/)
           Watcher: Ignoring (?-mix:^Gemfile)
           Watcher: Ignoring (?-mix:^Gemfile\.lock)
 Auto-regeneration: enabled for '/srv/jekyll'
LiveReload address: http://0.0.0.0:35729
[2023-12-11 09:43:42] INFO  WEBrick 1.8.1
[2023-12-11 09:43:42] INFO  ruby 3.1.2 (2022-04-12) [x86_64-linux-gnu]
[2023-12-11 09:43:42] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on /.
[2023-12-11 09:43:42] DEBUG unmount .
[2023-12-11 09:43:42] DEBUG Jekyll::Commands::Serve::Servlet is mounted on .
    Server address: http://0.0.0.0:8080
[2023-12-11 09:43:42] INFO  WEBrick::HTTPServer#start: pid=1 port=8080
  Server running... press ctrl-c to stop.`
```

**Comment by pollostrazon** [comment] 2023-12-11 10:08
> Good. Now go to `localhost:8080` and it should be fine.

![image](https://github.com/alshedivat/al-folio/assets/20032210/1fa668cf-4088-4b85-a4c1-f9a5ce4c07cf)
It just shows me the list of files in the webpage, but no preview of it. Also, it seems there is no content except from these .XML files.

**Comment by pollostrazon** [comment] 2023-12-11 10:10
Update: I had to rerun `docker compose up` for some reasons and stuff showed up! Ty so much!

This does not resolve the marmaid problem though...

**Comment by george-gca** [comment] 2024-01-03 01:46
@pollostrazon check if the mermaid problem is solved now.

**Comment by pourmand1376** [comment] 2024-01-03 05:33
> @pollostrazon check if the mermaid problem is solved now.

Is that a package update? If so, he needs to remove the image from the system and pull a new one.

**Comment by pollostrazon** [comment] 2024-01-03 10:31
I re-cloned the default repository in a new folder and re-pulled everything. `docker compose up` now works fine!
The issue is now solved for me!

**Comment by george-gca** [comment] 2024-01-03 16:31
Should we close this issue?

**Comment by pollostrazon** [comment] 2024-01-03 17:48
> Should we close this issue?

I think so. Now everything seems to be up and running. Ty!

**Closed** 2024-01-03 17:53 UTC
Labels: bug, docker

**Comment by pourmand1376** [comment] 2024-01-19 07:35
I think we should unpin this issue if it is silent in two weeks.

**Comment by sara-suzuki** [comment] 2024-12-24 20:04
I am having an issue where I get the error:

 exec /tmp/entry_point.sh: no such file or directory

**Comment by MikeMorenoDSP** [comment] 2024-12-27 17:32
Had this problem too with WSL downloaded v0.13.1 from "Releases".
Fixed by replacing line 4 from "docker-compose.yml" to `image: amirpourmand/al-folio:latest`
