### ISSUE TITLE
deploy crash with  Liquid Exception: Zero vectors can not be normalized in /REPO/_layout/post.html

### ISSUE THREAD

**Issue by MuhammedSabbagh** [alshedivat/al-folio#1203] opened 2023-02-22 14:05 UTC
**Acknowledge the following**
- [*] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [*] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [*] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
1- related posts which has been just recently added causes cibuild and deployment to fail after adding more than one post
2- when i push to gh-pages directly (which i've mistakenly done) i see the site doing all fine but posts return no article and any click to tags return me back home (or the about page to be precise)
log :
                   
  Liquid Exception: Zero vectors can not be normalized in /home/muhammed/development/muhammedsabbagh.github.io/_layouts/post.html
                    ------------------------------------------------
      Jekyll 4.3.2   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/muhammed/gems/gems/matrix-0.4.2/lib/matrix.rb:2398:in `normalize': Zero vectors can not be normalized (Vector::ZeroVectorError)
        from /home/muhammed/gems/gems/classifier-reborn-2.3.0/lib/classifier-reborn/lsi/content_node.rb:108:in `raw_vector_with'
        from /home/muhammed/gems/gems/classifier-reborn-2.3.0/lib/classifier-reborn/lsi.rb:386:in `node_for_content'
        from /home/muhammed/gems/gems/classifier-reborn-2.3.0/lib/classifier-reborn/lsi.rb:221:in `proximity_array_for_content'
        from /home/muhammed/gems/gems/classifier-reborn-2.3.0/lib/classifier-reborn/lsi.rb:296:in `find_related'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/related_posts.rb:45:in `lsi_related_posts'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/related_posts.rb:22:in `build'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/document.rb:403:in `related_posts'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/drops/site_drop.rb:58:in `related_posts'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/drops/drop.rb:128:in `public_send'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/drops/drop.rb:128:in `[]'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/drops/site_drop.rb:19:in `[]'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/context.rb:197:in `lookup_and_evaluate'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/variable_lookup.rb:48:in `block in evaluate'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/variable_lookup.rb:38:in `each_index'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/variable_lookup.rb:38:in `evaluate'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/context.rb:159:in `evaluate'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/for.rb:130:in `collection_segment'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/for.rb:74:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/inclusion.rb:16:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/tags/include.rb:208:in `block in render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/tags/include.rb:206:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:91:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `each'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `block in render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:43:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `each'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `block in render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:43:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:129:in `render_liquid'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:192:in `render_layout'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:161:in `place_in_layouts'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:93:in `render_document'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:557:in `block (2 levels) in render_docs'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `each'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `block in render_docs'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `each_value'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `render_docs'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:210:in `render'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        from /home/muhammed/gems/bin/jekyll:25:in `load'
        from /home/muhammed/gems/bin/jekyll:25:in `<top (required)>'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `load'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:23:in `run'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/lib/bundler/cli.rb:492:in `exec'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /home/muhammed/.local/share/gem/ruby/3.0.0/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
        from /home/muhammed/gems/bin/bundle:25:in `load'
        from /home/muhammed/gems/bin/bundle:25:in `<main>'

**To Reproduce**
1. have related posts enabled on _config.yml
2. have 2 or more posts (despite being linting checked)
3. use /bin/cibuild

**Expected behavior**
1- deployment should return a pass
2- i should see posts 

**Screenshots**

**System (please complete the following information):**
 - OS: EndeavourOS (Arch Linux) [64 bit x86]
 - chromium 108.0.5359.94 (Official Build) Arch Linux (64-bit)
 - Jekyll version [4.3.2]
- Ruby version [3.0.5p211]

**Additional context**
disabling related posts fixed the problem
![image](https://user-images.githubusercontent.com/72943950/220636495-c812fb4d-ad8b-46cb-ae43-2431c3e2f63a.png)
the post pages (despite having 2 posts or more) didn't show anything 

now i have passing deploy 
i can see posts
i can see websites

sorry if i have been rude in any place on this issue, and thank you!

**Comment by dh031200** [comment] 2023-03-02 15:10
@MuhammedSabbagh 

I have same issue. Finally I find solution.
In my case when I changed this option in `_config.yml`
true -> false
```
related_blog_posts:
  enabled: false
  max_related: 5
```
Deployment completed successfully.

**Comment by MuhammedSabbagh** [comment] 2023-03-06 19:24
> @MuhammedSabbagh
> 
> I have same issue. Finally I find solution. In my case when I changed this option in `_config.yml` true -> false
> 
> ```
> related_blog_posts:
>   enabled: false
>   max_related: 5
> ```
> 
> Deployment completed successfully.


i actually stated that in additional context aka "disabling related posts fixed the issue" so we are waiting to see if the feature gets fixed or not, the blog how ever works perfectly without it anyway

**Comment by george-gca** [comment] 2023-03-13 22:40
This works in the main repo, so something is not right.
Are any of your blog posts empty? As stated [here](https://github.com/jekyll/classifier-reborn/issues/64), empty or really small blog posts without meaningful words (i.e. only [stop words](https://en.wikipedia.org/wiki/Stop_words) used to (?) break LSI.

**Comment by Szymok** [comment] 2023-03-15 22:55
I have the same problem. Only have default and 2 non empty blog posts

**Comment by george-gca** [comment] 2023-03-15 23:46
Can you share some code, so I can try it?

**Comment by Szymok** [comment] 2023-03-15 23:58
[2023-03-06-ai-trends.md](https://github.com/alshedivat/al-folio/files/10985424/2023-03-06-ai-trends.md)
[2023-03-13-ai-writing.md](https://github.com/alshedivat/al-folio/files/10985425/2023-03-13-ai-writing.md)
This two posts probably couse the error, but i do not know why

**Comment by george-gca** [comment] 2023-03-16 00:17
Does it work when you run locally? For example, [running like this](https://george-gca.github.io/blog/2022/running-local-al-folio/)? But when about to get to the `bundle exec...` command, run it like this: `bundle exec jekyll serve --lsi`. I just tried these two posts in an offline setup and it worked just fine.

Just want to be sure that the problem is when uploading to a Github page, and doesn't happen when running locally.

**Comment by Szymok** [comment] 2023-03-16 01:00
Yep - it is working. I disabled the related_blog_posts and github pages also is working

**Comment by george-gca** [comment] 2023-03-16 01:11
Can you try to remove only these blog posts and enable again the related_blog_posts to check if the problem is with them?

**Comment by Szymok** [comment] 2023-03-16 01:16
After removing posts and enabling related_blog_posts - still the same problem

**Comment by george-gca** [comment] 2023-03-16 01:22
In your case, more specifically, might be a problem of the [classifier reborn](https://github.com/jekyll/classifier-reborn) plugin handling the [different characters](https://github.com/jekyll/classifier-reborn/issues/194) you use in your files due to your language. This is the plugin responsible of calculating related posts.

Just to be sure, try to move all your posts somewhere else, get the original posts from the repo and put them on the `_posts/` directory, and run with `related_blog_posts` enabled, check if this still happens.

**Comment by Szymok** [comment] 2023-03-16 01:30
Still error

**Comment by george-gca** [comment] 2023-03-16 01:44
I guess [this is the repo](https://github.com/Szymok/Szymok.github.io) you are using right? If this is the case, the problem lies in the announcements.

Internally, the announcements that sit in the `_news/` directory use the `layout: post`. The calculus for similar posts are made for every `post`, which means every page that uses `layout: post`. To fix this, you can either add more text to your announcements, to avoid [these errors](https://github.com/alshedivat/al-folio/issues/1203#issuecomment-1467074060), or add `related_posts: false` in your announcements.

**Comment by george-gca** [comment] 2023-03-16 02:17
@MuhammedSabbagh maybe this is the same issue for you?

**Comment by Szymok** [comment] 2023-03-16 16:01
>

Thank you, that works!

**Comment by thispath98** [comment] 2023-03-16 16:40
I got same Zero vector issue. When I started to deploy one posts in _posts directory, (there was no _posts dir. and posts, I deleted), the bug appears.

I can't handle through enabling related_blog_posts, because everytime I change and start to deploy, then same Zero vector error comes out. And then the commit was all gone, changes are reverted into original one as before I committed. Can you help me?

**Comment by george-gca** [comment] 2023-03-16 17:24
I don't think I understood. Can you explain it better @thispath98?

**Comment by george-gca** [comment] 2023-03-17 00:42
The error happens when `enabled: false`? That is really strange. Do you have some code that you can share?

It sounds like a really dumb question, but have you saved the file after changing it?

Also, is it working offline?

**Comment by thispath98** [comment] 2023-03-17 00:49
Yes. You can see my repo in [here](https://github.com/thispath98/thispath98.github.io/tree/gh-pages)

And Yes. I have saved the files(`_config.yml`, 1 post in `_posts` directory). Because I can't add or commit if there are no changes, yes I saved it.

Lastly, no. My website is totally fine to work. I wonder why I made a change and committed, but error occurs, repository has no record on commits.

**Comment by george-gca** [comment] 2023-03-17 01:28
Just saw your repo, and your main branch is empty 😨
All the Github actions configured on the repository (to build your site, make it online) is based on the main branch.

**Comment by george-gca** [comment] 2023-03-17 01:32
I would recommend creating your site again from the template, and making the modifications one by one, so it is easier to identify if and when it breaks. Also, try to run all the changes [offline](https://github.com/alshedivat/al-folio#local-setup-standard) before submitting to your branch to deploy it online. If you want a more step by step guide, you can check [this post](https://george-gca.github.io/blog/2022/running-local-al-folio/).

Just change the last step, when running locally, for `bundle exec jekyll serve --lsi` to enable the `related_posts` calculus.

**Comment by thispath98** [comment] 2023-03-17 01:37
Thanks! I agree with your opinion to start it from the bottom. I'll try it after reading manual exhaustively, Thank you!

**Comment by george-gca** [comment] 2023-03-17 01:57
You don't need to read a manual exhaustively, you just need to try to do small changes, one step at a time, and see how it goes. If it works like intended, great. If not, it is easy to revert. Just try again from scratch, make sure the original template run locally, then start doing the changes.

**Comment by thispath98** [comment] 2023-03-17 02:07
Thanks again. I would like to ask you something about `main` branch.

Previously, I deployed changes using `bin/deploy --user` after I add, commit, except pushing it to remote repository.

Can you explain how to push it to main branch? Or can you show some posts about this?

**Comment by dh031200** [comment] 2023-03-17 03:00
[here](https://github.com/alshedivat/al-folio#deployment) is deployment section.
Follow that process and push to `main` branch.

You don't need to do these.
```
(click to expand) Manual deployment to GitHub Pages:
(click to expand) Deployment to another hosting server (non GitHub Pages):
(click to expand) Deployment to a separate repository (advanced users only):
```

**Comment by george-gca** [comment] 2023-03-17 03:39
You don't need to deploy anything by hand. The whole template is already setup so your only work (after you configured your github repo according to the [To enable automatic deployment](https://github.com/alshedivat/al-folio#deployment) part) is to create your content and commit in your `main` branch.

The setup I would recommend (and that I used myself):
1 - create your own repo from this template by clicking [Use this template](https://docs.github.com/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) in the main repo page
2 - create your local setup following the instructions from [here](https://github.com/alshedivat/al-folio#local-setup-standard). Since I struggled myself in the beginning (I never used ruby or jekyll before), I [wrote a step-by-step tutorial](https://george-gca.github.io/blog/2022/running-local-al-folio/) on how to install rbenv and run your site locally
3 - everything is working locally, then follow the instructions on the [deployment section](https://github.com/alshedivat/al-folio#deployment), more specifically the part `For personal and organization webpages` and `To enable automatic deployment`
4 - make sure the default template works in `your-user.github.io`
5 - Then, and only then, you start to make your modifications

The workflow I recommend (and use):
1 - test your changes locally first, preferably making small changes at a time and commiting them 
2 - everything works, then push to you main repo

**Comment by george-gca** [comment] 2023-03-17 03:42
Also, @dh031200 I believe your `related_blog_posts` error was due to the same problem as [here](https://github.com/alshedivat/al-folio/issues/1203#issuecomment-1471152033)

**Comment by thispath98** [comment] 2023-03-17 03:54
Thank you @george-gca @dh031200 !! Now I know what I have to do 😊

**Closed** 2023-03-19 12:43 UTC
Labels: bug
