### ISSUE TITLE
Need to re run docker-compose up after every files change to display results

### ISSUE THREAD

**Issue by dzikrisyairozi** [alshedivat/al-folio#1640] opened 2023-08-07 13:49 UTC
**Acknowledge the following**
- [ ] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [ ] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [ ] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
This is so frustating, is it expected or there is any way to display changes after changing files without re run docker-compose up?

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Browser (and its version) [e.g. chrome, safari]
 - Jekyll version [e.g. 3.8.7]
- Ruby version [e.g. 2.6.5]

**Additional context**

**Comment by pourmand1376** [comment] 2023-08-20 05:55
Hi, This shouldn't be the case. I've just tested it and it is working without any problem. 

Can you run this command?
```
docker pull amirpourmand/al-folio

docker run -d \
  --name jekyll \
  -p 8080:8080 \
  -v $(pwd):/srv/jekyll \
  amirpourmand/al-folio \
  sh -c "rm -f Gemfile.lock && exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace"
```

**Comment by TheEliasBe** [comment] 2023-08-24 12:14
Live-Reloading does not work me either. I'm using the command `docker-compose -f docker-local.yml up`

**Comment by pourmand1376** [comment] 2023-08-24 15:31
Hi, This is a feature of Jekyll and it has nothing to do with our template. See [here](https://github.com/jekyll/jekyll/issues/2302).

However, we can use `watchy` to make changes to `config.yaml` appear instantly.

**Comment by george-gca** [comment] 2023-08-28 21:19
If these changes were made in yml files, as pointed out by @pourmand1376, it is a limitation of jekyll itself, so I think we should close this issue. Also I don't think it is worth tackling this.

**Comment by pourmand1376** [comment] 2023-08-29 04:04
Hi, @george-gca 

I agree.

**Comment by dzikrisyairozi** [comment] 2023-08-29 17:10
so is it possible to do that (live reload with docker) using this template?

**Comment by pourmand1376** [comment] 2023-08-29 18:53
> so is it possible to do that (live reload with docker) using this template? 

Yes, Just install npm and then watchy in docker and you should be able to reload the changes even if it is changes made in config.yaml file.

**Comment by sshourie** [comment] 2023-09-03 23:59
> > so is it possible to do that (live reload with docker) using this template?
> 
> Yes, Just install npm and then watchy in docker and you should be able to reload the changes even if it is changes made in config.yaml file.

Hi - I am using windows 10, and I'm facing this issue that I need to do "docker-compose up" for each change in any type of file (.html/.md... etc) to reflect on localhost.

I have added npm and watchy but it doesn't seem to work.
```
RUN apt-get install npm
RUN npm install watchy
```

Am I missing something?

**Comment by pourmand1376** [comment] 2023-09-04 06:04
You should run `docker-compose -f docker-local.yml up --build`. Did you run this?

**Comment by dzikrisyairozi** [comment] 2023-09-05 03:03
@pourmand1376 is it only happen on Windows 10? if we run on other like linux based os does this happen also?

**Comment by pourmand1376** [comment] 2023-09-05 05:05
It doesn't make any difference (no matter what OS you have). Jekyll doesn't support automatic reload of `_config.yaml`. 

I added a PR to resolve this issue manually.

**Comment by sshourie** [comment] 2023-09-06 03:51
> You should run `docker-compose -f docker-local.yml up --build`. Did you run this?

I tried this ```docker-compose -f docker-local.yml up --build```, unfortunately that did not work as intended. Any changes made to a ```.md``` or a `.html` file (then saving or committing the file) are not reflected on refreshing the local host (Win 10).

**Comment by george-gca** [comment] 2023-09-06 15:35
Just for the sake of testing, @sshourie try to change something in a .md or .html file and in your browser do a refresh with clean cache. Press [Shift + F5 on Chrome](https://support.google.com/chrome/answer/157179#zippy=%2Cwebpage-shortcuts) or [Ctrl + F5 on Firefox](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) to reload the page ignoring cached content, clean your browser history, or simply try it in a private session. See if that works without having to run docker compose again, to see if the browser is somehow keeping the old file in cache.

Also, which browser are you using?

**Comment by sshourie** [comment] 2023-09-06 23:43
> Just for the sake of testing, @sshourie try to change something in a .md or .html file and in your browser do a refresh with clean cache. Press [Shift + F5 on Chrome](https://support.google.com/chrome/answer/157179#zippy=%2Cwebpage-shortcuts) or [Ctrl + F5 on Firefox](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) to reload the page ignoring cached content, clean your browser history, or simply try it in a private session. See if that works without having to run docker compose again, to see if the browser is somehow keeping the old file in cache.
> 
> Also, which browser are you using?

I'm using Chrome in a private session and `Shift + F5` didn't work (didn't load saved changes to .md file)

**Comment by pourmand1376** [comment] 2023-09-11 06:13
> is this #1702 fix the issue?

Yes! You can test that via cloning the repository then using `docker compose build` and `docker compose up`.

**Comment by danimtz** [comment] 2023-09-17 18:51
For the record I am having the same issue as @sshourie using Docker Desktop on Windows 11

**Comment by george-gca** [comment] 2023-09-17 19:12
Are you using it in WSL, or natively on Windows? Which version of docker are you using?

It seems that a problem like this [was reported](https://github.com/docker/for-win/issues/5530) years ago on docker repository. Since this only happens on Windows, it seems more of an issue on docker side, not ours. I'm afraid we have our hands tied here. Please, consider opening [a bug for docker on windows](https://github.com/docker/for-win/issues/new/choose).

**Comment by TimChild** [comment] 2023-10-05 01:39
A quick fix seems to be to add `force_polling` to the Dockerfile `CMD`

```
CMD ["/bin/bash", "-c", "rm -f Gemfile.lock && exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace --force_polling"]
```

After making that change and running the container again, Jekyll automatically rebuilds after changing the `about.md` file, for example. 

You have to manually refresh the browser to see the changes, but it's still a lot better than having to re-run the whole docker container every time.

**Comment by george-gca** [comment] 2023-10-05 04:01
We can't escape refreshing the browser, but nice to see that there's a solution for the need to rerun the container.

**Comment by pourmand1376** [comment] 2023-10-07 06:33
I added `--force-pulling` option to command by default.

**Closed** 2023-10-07 06:34 UTC
Labels: enhancement, dependency, docker
